"""add lat lng to project

Revision ID: 7a0f3d61b32d
Revises: 5ef4f5ac3402
Create Date: 2026-09-18 13:25:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7a0f3d61b32d'
down_revision = '5ef4f5ac3402'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('project', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'longitude')
    op.drop_column('project', 'latitude')
    # ### end Alembic commands ###
