"""add boundary_geojson to project

Revision ID: 8b1f4d71c43e
Revises: 7a0f3d61b32d
Create Date: 2026-09-18 13:42:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8b1f4d71c43e'
down_revision = '7a0f3d61b32d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('boundary_geojson', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'boundary_geojson')
    # ### end Alembic commands ###
